### ISSUE TITLE
use case scripts are not executable

### ISSUE THREAD

**Issue by peterhack** [keptn/servicenow-service#5]
/servicenow-service/usecase/add-to-cart.sh and /servicenow-service/usecase/enable-promotion.sh are not set to executable (chmod +x) and had to be configured such to run the use case.  Attempts to run these scripts met with the following errors:
-bash: ./add-to-cart.sh: Permission denied
-bash: ./enable-promotion.sh: Permission denied

resolution: 
chmod +x ./*.sh

**Comment by jetzlstorfer** [comment]
Thanks for mentioning this. 
I've updated the files. 
Please note that you can always create a PR with suggestions for improvement :)
